### ISSUE TITLE
Adding storage freezee

### ISSUE THREAD

**Issue by bigretromike** [anime-db/anime-db#160]
When adding storage the progress bar is moving (gif?) and there is no progress, I added small folder for tests.
The log say:

```
Scan storage Folder:

Detected files for new item [Anime Land] Mobile Suit Gundam Thunderbolt December Sky (Dual Audio) (BDRip 720p Hi10P QAACx2) [EE69A6C6].mkv
Detected files for new item [Commie] Haikyuu!! Second Season - 14 [55DED0D6].mkv
Detected files for new item [HorribleSubs] Battery - 02 [720p].mkv
Detected files for new item [HorribleSubs] Kono Bijutsubu ni wa Mondai ga Aru! - 03 [1080p].mkv
Detected files for new item [HorribleSubs] Mahou Shoujo Naria Girls - 03 [1080p].mkv
Detected files for new item [HorribleSubs] Planetarian - 03 [1080p].mkv
Detected files for new item [Impatience] Fate Kaleid Liner Prisma Illya 3rei!! - 03 [720p][A163DBD5].mkv
Detected files for new item [Kaitou]_Onara_Gorou_-_02_[720p][10bit][40F0D37C].mkv
Detected files for new item [Kaitou]_Ozmafia!!_-_03_[720p][10bit][CDE45C5F].mkv
Time: 49 s.

C:\anime-db\AnimeDB>
```

And after 10minuts nothing. 
I do get notice:

"
Detected files for new item [Commie] Haikyuu!! Second Season - 14 [55DED0D6] on storage Folder (All notices) " and for others files to but when I click it It take me to "Search items on AniDB.net" and search wont find anything even if i cut out [fansub] [crc] and episode number. 

Maybe those to are related.

**Comment by peter-gribanov** [comment]
@bigretromike i can't now answer on your question. I necessarily will answer you later.
Now you can look [add storage guide](http://anime-db.org/en/guide/storage/add.html) and [skan storage guide](http://anime-db.org/en/guide/storage/scan.html).

**Comment by peter-gribanov** [comment]
Sorry for waiting.
Now the problem is solved.
You can update your application or download the latest version from [anime-db.org](http://anime-db.org/).

## Recommendations

The application and documentation mentioned the recommendations for organizing the file structure in the repository. Group movies and serials into folders.
Example for your files:

```
Mobile Suit Gundam Thunderbolt December Sky
    └ [Anime Land] Mobile Suit Gundam Thunderbolt December Sky (Dual Audio) (BDRip 720p Hi10P QAACx2) [EE69A6C6].mkv
Haikyuu!!
    ├ First Season
    |    └ ...
    └ Second Season
         ├ ...
         ├ [Commie] Haikyuu!! Second Season - 14 [55DED0D6].mkv
         └ ...
Battery
    ├ [HorribleSubs] Battery - 01 [720p].mkv
    ├ [HorribleSubs] Battery - 02 [720p].mkv
    └ ...
Kono Bijutsubu ni wa Mondai ga Aru!
    ├ [HorribleSubs] Kono Bijutsubu ni wa Mondai ga Aru! - 01 [1080p].mkv
    ├ [HorribleSubs] Kono Bijutsubu ni wa Mondai ga Aru! - 02 [1080p].mkv
    ├ [HorribleSubs] Kono Bijutsubu ni wa Mondai ga Aru! - 03 [1080p].mkv
    └ ...
Mahou Shoujo Naria Girls
    ├ [HorribleSubs] Mahou Shoujo Naria Girls - 01 [1080p].mkv
    ├ [HorribleSubs] Mahou Shoujo Naria Girls - 02 [1080p].mkv
    ├ [HorribleSubs] Mahou Shoujo Naria Girls - 03 [1080p].mkv
    └ ...
Planetarian
    ├ [HorribleSubs] Planetarian - 01 [1080p].mkv
    ├ [HorribleSubs] Planetarian - 02 [1080p].mkv
    ├ [HorribleSubs] Planetarian - 03 [1080p].mkv
    └ ...
Fate Kaleid Liner Prisma Illya 3rei!!
    ├ [Impatience] Fate Kaleid Liner Prisma Illya 3rei!! - 01 [720p][A163DBD5].mkv
    ├ [Impatience] Fate Kaleid Liner Prisma Illya 3rei!! - 02 [720p][A163DBD5].mkv
    ├ [Impatience] Fate Kaleid Liner Prisma Illya 3rei!! - 03 [720p][A163DBD5].mkv
    └ ...
Onara Gorou
    ├ [Kaitou]_Onara_Gorou_-_01_[720p][10bit][40F0D37C].mkv
    ├ [Kaitou]_Onara_Gorou_-_02_[720p][10bit][40F0D37C].mkv
    └ ...
Ozmafia!!
    ├ [Kaitou]_Ozmafia!!_-_01_[720p][10bit][CDE45C5F].mkv
    ├ [Kaitou]_Ozmafia!!_-_02_[720p][10bit][CDE45C5F].mkv
    ├ [Kaitou]_Ozmafia!!_-_03_[720p][10bit][CDE45C5F].mkv
    └ ...
```

As a result, the name of the folder contains only the name of the anime, and all technical information is described in the titles of the series themselves.

This is not an obligatory rule. This is only a recommendation.
The storage scanner analyzes the names of files and directories in the root of the repository. When new files or folders are found, it removes all the technical information from the name and tries to find an anime by name. If the scanner can only find one anime by the name of the file/folder, then the anime will automatically be added to your database.

This is to make it easier for you to fill your database.

**Comment by bigretromike** [comment]
why not look anime by its hash sum ? then You won't have problem with wrong names/series reboots etc.

**Comment by peter-gribanov** [comment]
> why not look anime by its hash sum ?

How to determine that this hash sum corresponds to this film or series? The same movie can be re-cast in different qualities, in different formats, with different voice acting and with different built-in subtitles. And the hash will be different every one. But the name of the film is universal.
In addition, all services support only search by name.

This problem is relevant for those who download anime. Now gaining popularity, viewing anime online.
Now we are working in this direction.

But thanks for the idea.

**Comment by bigretromike** [comment]
As 'name' is universal (but can give you a lot of problems) the hash is 1to1. Its true that anime community started to do this (from what i know) and the biggest collection is at anidb, where there is A LOT of those community driven. With Hash you have 99,99999999% hit. also if you download videos and `care` about them you in some point of time will check hash yourself (if you started to having corrupted videos) ;-)

Also I will close this as you say you resolve my problem. Im not 100% user of anime-db, but Im checking it from time to time 👍 its good to have multiply options - so its just my 2cents for improvement.

**Comment by peter-gribanov** [comment]
Thanks for help
